services:
  mysql:
    image: mysql:8.4
    container_name: traqueur-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: traqueur_flotte
      MYSQL_USER: traqueur
      MYSQL_PASSWORD: traqueur123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: