spring.datasource.url=jdbc:mysql://localhost:3306/traqueur_flotte
spring.datasource.username=traqueur
spring.datasource.password=traqueur123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect